-- ================================================================
-- Migration 009: Master Chart of Accounts + Account Codes
-- Safe to re-run (idempotent). Handles existing tables.
-- ================================================================

-- 1. Extend categories table
ALTER TABLE categories
  ADD COLUMN IF NOT EXISTS code       text,
  ADD COLUMN IF NOT EXISTS parent_id  uuid REFERENCES categories(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS is_active  boolean NOT NULL DEFAULT true;

CREATE INDEX IF NOT EXISTS categories_parent ON categories(parent_id) WHERE parent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS categories_code   ON categories(org_id, code);

-- 2. Create master_coa if it doesn't exist
-- type is nullable — inactive placeholder rows have no type
CREATE TABLE IF NOT EXISTS master_coa (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  code        text NOT NULL UNIQUE,
  label       text,
  type        text,
  group_name  text,
  description text,
  is_common   boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- 3. Fix schema on existing tables (idempotent)
ALTER TABLE master_coa ALTER COLUMN type   DROP NOT NULL;
ALTER TABLE master_coa ALTER COLUMN label  DROP NOT NULL;

-- Drop old check constraint if it exists, then add correct one
DO $$
BEGIN
  ALTER TABLE master_coa DROP CONSTRAINT IF EXISTS master_coa_type_check;
  ALTER TABLE master_coa ADD CONSTRAINT master_coa_type_check
    CHECK (type IS NULL OR type IN ('income','expense','asset','liability','equity'));
EXCEPTION WHEN others THEN NULL;
END $$;

-- 4. RLS
ALTER TABLE master_coa ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS master_coa_read ON master_coa;
CREATE POLICY master_coa_read ON master_coa FOR SELECT USING (auth.role() = 'authenticated');

-- 5. Seed all 000-999 slots

INSERT INTO master_coa (code, label, type, group_name, description, is_common) VALUES
('000', 'System / Opening Balance', null, null, null, false),
('001', 'Opening Balance Offset', null, null, null, false),
('002', null, null, null, null, false),
('003', null, null, null, null, false),
('004', null, null, null, null, false),
('005', null, null, null, null, false),
('006', null, null, null, null, false),
('007', null, null, null, null, false),
('008', null, null, null, null, false),
('009', null, null, null, null, false),
('010', null, null, null, null, false),
('011', null, null, null, null, false),
('012', null, null, null, null, false),
('013', null, null, null, null, false),
('014', null, null, null, null, false),
('015', null, null, null, null, false),
('016', null, null, null, null, false),
('017', null, null, null, null, false),
('018', null, null, null, null, false),
('019', null, null, null, null, false),
('020', null, null, null, null, false),
('021', null, null, null, null, false),
('022', null, null, null, null, false),
('023', null, null, null, null, false),
('024', null, null, null, null, false),
('025', null, null, null, null, false),
('026', null, null, null, null, false),
('027', null, null, null, null, false),
('028', null, null, null, null, false),
('029', null, null, null, null, false),
('030', null, null, null, null, false),
('031', null, null, null, null, false),
('032', null, null, null, null, false),
('033', null, null, null, null, false),
('034', null, null, null, null, false),
('035', null, null, null, null, false),
('036', null, null, null, null, false),
('037', null, null, null, null, false),
('038', null, null, null, null, false),
('039', null, null, null, null, false),
('040', null, null, null, null, false),
('041', null, null, null, null, false),
('042', null, null, null, null, false),
('043', null, null, null, null, false),
('044', null, null, null, null, false),
('045', null, null, null, null, false),
('046', null, null, null, null, false),
('047', null, null, null, null, false),
('048', null, null, null, null, false),
('049', null, null, null, null, false),
('050', null, null, null, null, false),
('051', null, null, null, null, false),
('052', null, null, null, null, false),
('053', null, null, null, null, false),
('054', null, null, null, null, false),
('055', null, null, null, null, false),
('056', null, null, null, null, false),
('057', null, null, null, null, false),
('058', null, null, null, null, false),
('059', null, null, null, null, false),
('060', null, null, null, null, false),
('061', null, null, null, null, false),
('062', null, null, null, null, false),
('063', null, null, null, null, false),
('064', null, null, null, null, false),
('065', null, null, null, null, false),
('066', null, null, null, null, false),
('067', null, null, null, null, false),
('068', null, null, null, null, false),
('069', null, null, null, null, false),
('070', null, null, null, null, false),
('071', null, null, null, null, false),
('072', null, null, null, null, false),
('073', null, null, null, null, false),
('074', null, null, null, null, false),
('075', null, null, null, null, false),
('076', null, null, null, null, false),
('077', null, null, null, null, false),
('078', null, null, null, null, false),
('079', null, null, null, null, false),
('080', null, null, null, null, false),
('081', null, null, null, null, false),
('082', null, null, null, null, false),
('083', null, null, null, null, false),
('084', null, null, null, null, false),
('085', null, null, null, null, false),
('086', null, null, null, null, false),
('087', null, null, null, null, false),
('088', null, null, null, null, false),
('089', null, null, null, null, false),
('090', null, null, null, null, false),
('091', null, null, null, null, false),
('092', null, null, null, null, false),
('093', null, null, null, null, false),
('094', null, null, null, null, false),
('095', null, null, null, null, false),
('096', null, null, null, null, false),
('097', null, null, null, null, false),
('098', null, null, null, null, false),
('099', null, null, null, null, false),
('100', 'Cash & Bank Accounts', 'asset', 'Current Assets', 'All cash and bank accounts', true),
('101', 'Petty Cash', 'asset', 'Current Assets', 'Small cash on hand', false),
('102', 'Cash on Hand', 'asset', 'Current Assets', null, false),
('103', null, null, null, null, false),
('104', null, null, null, null, false),
('105', null, null, null, null, false),
('106', null, null, null, null, false),
('107', null, null, null, null, false),
('108', null, null, null, null, false),
('109', null, null, null, null, false),
('110', 'Cheque / Transaction Account', 'asset', 'Current Assets', 'Primary everyday bank account', true),
('111', 'Business Cheque Account', 'asset', 'Current Assets', null, false),
('112', 'Trust Account', 'asset', 'Current Assets', null, false),
('113', null, null, null, null, false),
('114', null, null, null, null, false),
('115', null, null, null, null, false),
('116', null, null, null, null, false),
('117', null, null, null, null, false),
('118', null, null, null, null, false),
('119', null, null, null, null, false),
('120', 'Savings Account', 'asset', 'Current Assets', 'High-interest savings account', true),
('121', 'Offset Account', 'asset', 'Current Assets', 'Mortgage offset account', false),
('122', 'Term Deposit', 'asset', 'Current Assets', null, false),
('123', null, null, null, null, false),
('124', null, null, null, null, false),
('125', null, null, null, null, false),
('126', null, null, null, null, false),
('127', null, null, null, null, false),
('128', null, null, null, null, false),
('129', null, null, null, null, false),
('130', 'Foreign Currency Account', 'asset', 'Current Assets', null, false),
('131', null, null, null, null, false),
('132', null, null, null, null, false),
('133', null, null, null, null, false),
('134', null, null, null, null, false),
('135', null, null, null, null, false),
('136', null, null, null, null, false),
('137', null, null, null, null, false),
('138', null, null, null, null, false),
('139', null, null, null, null, false),
('140', 'Accounts Receivable', 'asset', 'Current Assets', 'Money owed by customers', false),
('141', 'Trade Receivables', 'asset', 'Current Assets', null, false),
('142', 'Other Receivables', 'asset', 'Current Assets', null, false),
('143', null, null, null, null, false),
('144', null, null, null, null, false),
('145', null, null, null, null, false),
('146', null, null, null, null, false),
('147', null, null, null, null, false),
('148', null, null, null, null, false),
('149', null, null, null, null, false),
('150', 'Prepayments', 'asset', 'Current Assets', 'Expenses paid in advance', false),
('151', 'GST Receivable', 'asset', 'Current Assets', 'GST input tax credits', false),
('152', 'Income Tax Receivable', 'asset', 'Current Assets', null, false),
('153', null, null, null, null, false),
('154', null, null, null, null, false),
('155', null, null, null, null, false),
('156', null, null, null, null, false),
('157', null, null, null, null, false),
('158', null, null, null, null, false),
('159', null, null, null, null, false),
('160', null, null, null, null, false),
('161', null, null, null, null, false),
('162', null, null, null, null, false),
('163', null, null, null, null, false),
('164', null, null, null, null, false),
('165', null, null, null, null, false),
('166', null, null, null, null, false),
('167', null, null, null, null, false),
('168', null, null, null, null, false),
('169', null, null, null, null, false),
('170', null, null, null, null, false),
('171', null, null, null, null, false),
('172', null, null, null, null, false),
('173', null, null, null, null, false),
('174', null, null, null, null, false),
('175', null, null, null, null, false),
('176', null, null, null, null, false),
('177', null, null, null, null, false),
('178', null, null, null, null, false),
('179', null, null, null, null, false),
('180', null, null, null, null, false),
('181', null, null, null, null, false),
('182', null, null, null, null, false),
('183', null, null, null, null, false),
('184', null, null, null, null, false),
('185', null, null, null, null, false),
('186', null, null, null, null, false),
('187', null, null, null, null, false),
('188', null, null, null, null, false),
('189', null, null, null, null, false),
('190', null, null, null, null, false),
('191', null, null, null, null, false),
('192', null, null, null, null, false),
('193', null, null, null, null, false),
('194', null, null, null, null, false),
('195', null, null, null, null, false),
('196', null, null, null, null, false),
('197', null, null, null, null, false),
('198', null, null, null, null, false),
('199', null, null, null, null, false),
('200', 'Investments', 'asset', 'Investments', 'Total investment holdings', true),
('201', 'Shares & ETFs', 'asset', 'Investments', 'Listed equities and ETFs', true),
('202', 'Managed Funds', 'asset', 'Investments', null, false),
('203', 'Bonds & Fixed Interest', 'asset', 'Investments', null, false),
('204', 'Cryptocurrency', 'asset', 'Investments', null, false),
('205', 'Unlisted Investments', 'asset', 'Investments', null, false),
('206', null, null, null, null, false),
('207', null, null, null, null, false),
('208', null, null, null, null, false),
('209', null, null, null, null, false),
('210', 'Investment Property', 'asset', 'Investments', null, false),
('211', null, null, null, null, false),
('212', null, null, null, null, false),
('213', null, null, null, null, false),
('214', null, null, null, null, false),
('215', null, null, null, null, false),
('216', null, null, null, null, false),
('217', null, null, null, null, false),
('218', null, null, null, null, false),
('219', null, null, null, null, false),
('220', 'Superannuation', 'asset', 'Investments', 'Super fund balance', true),
('221', null, null, null, null, false),
('222', null, null, null, null, false),
('223', null, null, null, null, false),
('224', null, null, null, null, false),
('225', null, null, null, null, false),
('226', null, null, null, null, false),
('227', null, null, null, null, false),
('228', null, null, null, null, false),
('229', null, null, null, null, false),
('230', null, null, null, null, false),
('231', null, null, null, null, false),
('232', null, null, null, null, false),
('233', null, null, null, null, false),
('234', null, null, null, null, false),
('235', null, null, null, null, false),
('236', null, null, null, null, false),
('237', null, null, null, null, false),
('238', null, null, null, null, false),
('239', null, null, null, null, false),
('240', null, null, null, null, false),
('241', null, null, null, null, false),
('242', null, null, null, null, false),
('243', null, null, null, null, false),
('244', null, null, null, null, false),
('245', null, null, null, null, false),
('246', null, null, null, null, false),
('247', null, null, null, null, false),
('248', null, null, null, null, false),
('249', null, null, null, null, false),
('250', null, null, null, null, false),
('251', null, null, null, null, false),
('252', null, null, null, null, false),
('253', null, null, null, null, false),
('254', null, null, null, null, false),
('255', null, null, null, null, false),
('256', null, null, null, null, false),
('257', null, null, null, null, false),
('258', null, null, null, null, false),
('259', null, null, null, null, false),
('260', null, null, null, null, false),
('261', null, null, null, null, false),
('262', null, null, null, null, false),
('263', null, null, null, null, false),
('264', null, null, null, null, false),
('265', null, null, null, null, false),
('266', null, null, null, null, false),
('267', null, null, null, null, false),
('268', null, null, null, null, false),
('269', null, null, null, null, false),
('270', null, null, null, null, false),
('271', null, null, null, null, false),
('272', null, null, null, null, false),
('273', null, null, null, null, false),
('274', null, null, null, null, false),
('275', null, null, null, null, false),
('276', null, null, null, null, false),
('277', null, null, null, null, false),
('278', null, null, null, null, false),
('279', null, null, null, null, false),
('280', null, null, null, null, false),
('281', null, null, null, null, false),
('282', null, null, null, null, false),
('283', null, null, null, null, false),
('284', null, null, null, null, false),
('285', null, null, null, null, false),
('286', null, null, null, null, false),
('287', null, null, null, null, false),
('288', null, null, null, null, false),
('289', null, null, null, null, false),
('290', null, null, null, null, false),
('291', null, null, null, null, false),
('292', null, null, null, null, false),
('293', null, null, null, null, false),
('294', null, null, null, null, false),
('295', null, null, null, null, false),
('296', null, null, null, null, false),
('297', null, null, null, null, false),
('298', null, null, null, null, false),
('299', null, null, null, null, false),
('300', 'Fixed Assets', 'asset', 'Fixed Assets', 'Long-term tangible assets', false),
('301', 'Land', 'asset', 'Fixed Assets', null, false),
('302', 'Buildings', 'asset', 'Fixed Assets', null, false),
('303', null, null, null, null, false),
('304', null, null, null, null, false),
('305', null, null, null, null, false),
('306', null, null, null, null, false),
('307', null, null, null, null, false),
('308', null, null, null, null, false),
('309', null, null, null, null, false),
('310', 'Motor Vehicle', 'asset', 'Fixed Assets', null, true),
('311', null, null, null, null, false),
('312', null, null, null, null, false),
('313', null, null, null, null, false),
('314', null, null, null, null, false),
('315', null, null, null, null, false),
('316', null, null, null, null, false),
('317', null, null, null, null, false),
('318', null, null, null, null, false),
('319', null, null, null, null, false),
('320', 'Office Equipment', 'asset', 'Fixed Assets', null, false),
('321', null, null, null, null, false),
('322', null, null, null, null, false),
('323', null, null, null, null, false),
('324', null, null, null, null, false),
('325', null, null, null, null, false),
('326', null, null, null, null, false),
('327', null, null, null, null, false),
('328', null, null, null, null, false),
('329', null, null, null, null, false),
('330', 'Computer Equipment', 'asset', 'Fixed Assets', null, false),
('331', null, null, null, null, false),
('332', null, null, null, null, false),
('333', null, null, null, null, false),
('334', null, null, null, null, false),
('335', null, null, null, null, false),
('336', null, null, null, null, false),
('337', null, null, null, null, false),
('338', null, null, null, null, false),
('339', null, null, null, null, false),
('340', 'Furniture & Fittings', 'asset', 'Fixed Assets', null, false),
('341', null, null, null, null, false),
('342', null, null, null, null, false),
('343', null, null, null, null, false),
('344', null, null, null, null, false),
('345', null, null, null, null, false),
('346', null, null, null, null, false),
('347', null, null, null, null, false),
('348', null, null, null, null, false),
('349', null, null, null, null, false),
('350', null, null, null, null, false),
('351', null, null, null, null, false),
('352', null, null, null, null, false),
('353', null, null, null, null, false),
('354', null, null, null, null, false),
('355', null, null, null, null, false),
('356', null, null, null, null, false),
('357', null, null, null, null, false),
('358', null, null, null, null, false),
('359', null, null, null, null, false),
('360', null, null, null, null, false),
('361', null, null, null, null, false),
('362', null, null, null, null, false),
('363', null, null, null, null, false),
('364', null, null, null, null, false),
('365', null, null, null, null, false),
('366', null, null, null, null, false),
('367', null, null, null, null, false),
('368', null, null, null, null, false),
('369', null, null, null, null, false),
('370', null, null, null, null, false),
('371', null, null, null, null, false),
('372', null, null, null, null, false),
('373', null, null, null, null, false),
('374', null, null, null, null, false),
('375', null, null, null, null, false),
('376', null, null, null, null, false),
('377', null, null, null, null, false),
('378', null, null, null, null, false),
('379', null, null, null, null, false),
('380', null, null, null, null, false),
('381', null, null, null, null, false),
('382', null, null, null, null, false),
('383', null, null, null, null, false),
('384', null, null, null, null, false),
('385', null, null, null, null, false),
('386', null, null, null, null, false),
('387', null, null, null, null, false),
('388', null, null, null, null, false),
('389', null, null, null, null, false),
('390', 'Accumulated Depreciation', 'asset', 'Fixed Assets', 'Contra asset account', false),
('391', null, null, null, null, false),
('392', null, null, null, null, false),
('393', null, null, null, null, false),
('394', null, null, null, null, false),
('395', null, null, null, null, false),
('396', null, null, null, null, false),
('397', null, null, null, null, false),
('398', null, null, null, null, false),
('399', null, null, null, null, false),
('400', 'Credit Cards', 'liability', 'Current Liabilities', 'Credit card balances owing', true),
('401', 'ANZ Credit Card', 'liability', 'Current Liabilities', null, false),
('402', 'Westpac Credit Card', 'liability', 'Current Liabilities', null, false),
('403', 'CBA Credit Card', 'liability', 'Current Liabilities', null, false),
('404', 'NAB Credit Card', 'liability', 'Current Liabilities', null, false),
('405', null, null, null, null, false),
('406', null, null, null, null, false),
('407', null, null, null, null, false),
('408', null, null, null, null, false),
('409', null, null, null, null, false),
('410', 'Accounts Payable', 'liability', 'Current Liabilities', 'Bills owed to suppliers', false),
('411', null, null, null, null, false),
('412', null, null, null, null, false),
('413', null, null, null, null, false),
('414', null, null, null, null, false),
('415', null, null, null, null, false),
('416', null, null, null, null, false),
('417', null, null, null, null, false),
('418', null, null, null, null, false),
('419', null, null, null, null, false),
('420', 'GST Payable', 'liability', 'Current Liabilities', 'Net GST owing to ATO', false),
('421', 'PAYG Withholding Payable', 'liability', 'Current Liabilities', null, false),
('422', 'Income Tax Payable', 'liability', 'Current Liabilities', null, false),
('423', 'FBT Payable', 'liability', 'Current Liabilities', 'Fringe benefits tax', false),
('424', null, null, null, null, false),
('425', null, null, null, null, false),
('426', null, null, null, null, false),
('427', null, null, null, null, false),
('428', null, null, null, null, false),
('429', null, null, null, null, false),
('430', 'Wages Payable', 'liability', 'Current Liabilities', null, false),
('431', 'Superannuation Payable', 'liability', 'Current Liabilities', null, false),
('432', 'Annual Leave Payable', 'liability', 'Current Liabilities', null, false),
('433', null, null, null, null, false),
('434', null, null, null, null, false),
('435', null, null, null, null, false),
('436', null, null, null, null, false),
('437', null, null, null, null, false),
('438', null, null, null, null, false),
('439', null, null, null, null, false),
('440', 'Accrued Expenses', 'liability', 'Current Liabilities', 'Expenses incurred not yet paid', false),
('441', null, null, null, null, false),
('442', null, null, null, null, false),
('443', null, null, null, null, false),
('444', null, null, null, null, false),
('445', null, null, null, null, false),
('446', null, null, null, null, false),
('447', null, null, null, null, false),
('448', null, null, null, null, false),
('449', null, null, null, null, false),
('450', 'Buy Now Pay Later', 'liability', 'Current Liabilities', 'Afterpay, Zip, Klarna etc.', true),
('451', null, null, null, null, false),
('452', null, null, null, null, false),
('453', null, null, null, null, false),
('454', null, null, null, null, false),
('455', null, null, null, null, false),
('456', null, null, null, null, false),
('457', null, null, null, null, false),
('458', null, null, null, null, false),
('459', null, null, null, null, false),
('460', null, null, null, null, false),
('461', null, null, null, null, false),
('462', null, null, null, null, false),
('463', null, null, null, null, false),
('464', null, null, null, null, false),
('465', null, null, null, null, false),
('466', null, null, null, null, false),
('467', null, null, null, null, false),
('468', null, null, null, null, false),
('469', null, null, null, null, false),
('470', null, null, null, null, false),
('471', null, null, null, null, false),
('472', null, null, null, null, false),
('473', null, null, null, null, false),
('474', null, null, null, null, false),
('475', null, null, null, null, false),
('476', null, null, null, null, false),
('477', null, null, null, null, false),
('478', null, null, null, null, false),
('479', null, null, null, null, false),
('480', null, null, null, null, false),
('481', null, null, null, null, false),
('482', null, null, null, null, false),
('483', null, null, null, null, false),
('484', null, null, null, null, false),
('485', null, null, null, null, false),
('486', null, null, null, null, false),
('487', null, null, null, null, false),
('488', null, null, null, null, false),
('489', null, null, null, null, false),
('490', null, null, null, null, false),
('491', null, null, null, null, false),
('492', null, null, null, null, false),
('493', null, null, null, null, false),
('494', null, null, null, null, false),
('495', null, null, null, null, false),
('496', null, null, null, null, false),
('497', null, null, null, null, false),
('498', null, null, null, null, false),
('499', null, null, null, null, false),
('500', 'Loans & Borrowings', 'liability', 'Non-Current Liabilities', 'All loan facilities', false),
('501', null, null, null, null, false),
('502', null, null, null, null, false),
('503', null, null, null, null, false),
('504', null, null, null, null, false),
('505', null, null, null, null, false),
('506', null, null, null, null, false),
('507', null, null, null, null, false),
('508', null, null, null, null, false),
('509', null, null, null, null, false),
('510', 'Home Loan / Mortgage', 'liability', 'Non-Current Liabilities', null, true),
('511', null, null, null, null, false),
('512', null, null, null, null, false),
('513', null, null, null, null, false),
('514', null, null, null, null, false),
('515', null, null, null, null, false),
('516', null, null, null, null, false),
('517', null, null, null, null, false),
('518', null, null, null, null, false),
('519', null, null, null, null, false),
('520', 'Car Loan', 'liability', 'Non-Current Liabilities', null, true),
('521', null, null, null, null, false),
('522', null, null, null, null, false),
('523', null, null, null, null, false),
('524', null, null, null, null, false),
('525', null, null, null, null, false),
('526', null, null, null, null, false),
('527', null, null, null, null, false),
('528', null, null, null, null, false),
('529', null, null, null, null, false),
('530', 'Personal Loan', 'liability', 'Non-Current Liabilities', null, true),
('531', null, null, null, null, false),
('532', null, null, null, null, false),
('533', null, null, null, null, false),
('534', null, null, null, null, false),
('535', null, null, null, null, false),
('536', null, null, null, null, false),
('537', null, null, null, null, false),
('538', null, null, null, null, false),
('539', null, null, null, null, false),
('540', 'HELP / HECS Debt', 'liability', 'Non-Current Liabilities', 'Commonwealth student loan', true),
('541', null, null, null, null, false),
('542', null, null, null, null, false),
('543', null, null, null, null, false),
('544', null, null, null, null, false),
('545', null, null, null, null, false),
('546', null, null, null, null, false),
('547', null, null, null, null, false),
('548', null, null, null, null, false),
('549', null, null, null, null, false),
('550', 'Business Loan', 'liability', 'Non-Current Liabilities', null, false),
('551', null, null, null, null, false),
('552', null, null, null, null, false),
('553', null, null, null, null, false),
('554', null, null, null, null, false),
('555', null, null, null, null, false),
('556', null, null, null, null, false),
('557', null, null, null, null, false),
('558', null, null, null, null, false),
('559', null, null, null, null, false),
('560', null, null, null, null, false),
('561', null, null, null, null, false),
('562', null, null, null, null, false),
('563', null, null, null, null, false),
('564', null, null, null, null, false),
('565', null, null, null, null, false),
('566', null, null, null, null, false),
('567', null, null, null, null, false),
('568', null, null, null, null, false),
('569', null, null, null, null, false),
('570', null, null, null, null, false),
('571', null, null, null, null, false),
('572', null, null, null, null, false),
('573', null, null, null, null, false),
('574', null, null, null, null, false),
('575', null, null, null, null, false),
('576', null, null, null, null, false),
('577', null, null, null, null, false),
('578', null, null, null, null, false),
('579', null, null, null, null, false),
('580', null, null, null, null, false),
('581', null, null, null, null, false),
('582', null, null, null, null, false),
('583', null, null, null, null, false),
('584', null, null, null, null, false),
('585', null, null, null, null, false),
('586', null, null, null, null, false),
('587', null, null, null, null, false),
('588', null, null, null, null, false),
('589', null, null, null, null, false),
('590', null, null, null, null, false),
('591', null, null, null, null, false),
('592', null, null, null, null, false),
('593', null, null, null, null, false),
('594', null, null, null, null, false),
('595', null, null, null, null, false),
('596', null, null, null, null, false),
('597', null, null, null, null, false),
('598', null, null, null, null, false),
('599', null, null, null, null, false),
('600', 'Owner''s Equity', 'equity', 'Equity', null, true),
('601', null, null, null, null, false),
('602', null, null, null, null, false),
('603', null, null, null, null, false),
('604', null, null, null, null, false),
('605', null, null, null, null, false),
('606', null, null, null, null, false),
('607', null, null, null, null, false),
('608', null, null, null, null, false),
('609', null, null, null, null, false),
('610', 'Retained Earnings', 'equity', 'Equity', 'Accumulated profits not distributed', false),
('611', null, null, null, null, false),
('612', null, null, null, null, false),
('613', null, null, null, null, false),
('614', null, null, null, null, false),
('615', null, null, null, null, false),
('616', null, null, null, null, false),
('617', null, null, null, null, false),
('618', null, null, null, null, false),
('619', null, null, null, null, false),
('620', 'Drawings', 'equity', 'Equity', 'Owner withdrawals from business', true),
('621', null, null, null, null, false),
('622', null, null, null, null, false),
('623', null, null, null, null, false),
('624', null, null, null, null, false),
('625', null, null, null, null, false),
('626', null, null, null, null, false),
('627', null, null, null, null, false),
('628', null, null, null, null, false),
('629', null, null, null, null, false),
('630', 'Share Capital', 'equity', 'Equity', 'Paid-up share capital', false),
('631', null, null, null, null, false),
('632', null, null, null, null, false),
('633', null, null, null, null, false),
('634', null, null, null, null, false),
('635', null, null, null, null, false),
('636', null, null, null, null, false),
('637', null, null, null, null, false),
('638', null, null, null, null, false),
('639', null, null, null, null, false),
('640', 'Trust Corpus', 'equity', 'Trust Equity', 'Original trust settlement', false),
('641', 'Retained Trust Income', 'equity', 'Trust Equity', null, false),
('642', 'Settlor Contribution', 'equity', 'Trust Equity', null, false),
('643', null, null, null, null, false),
('644', null, null, null, null, false),
('645', null, null, null, null, false),
('646', null, null, null, null, false),
('647', null, null, null, null, false),
('648', null, null, null, null, false),
('649', null, null, null, null, false),
('650', null, null, null, null, false),
('651', null, null, null, null, false),
('652', null, null, null, null, false),
('653', null, null, null, null, false),
('654', null, null, null, null, false),
('655', null, null, null, null, false),
('656', null, null, null, null, false),
('657', null, null, null, null, false),
('658', null, null, null, null, false),
('659', null, null, null, null, false),
('660', null, null, null, null, false),
('661', null, null, null, null, false),
('662', null, null, null, null, false),
('663', null, null, null, null, false),
('664', null, null, null, null, false),
('665', null, null, null, null, false),
('666', null, null, null, null, false),
('667', null, null, null, null, false),
('668', null, null, null, null, false),
('669', null, null, null, null, false),
('670', null, null, null, null, false),
('671', null, null, null, null, false),
('672', null, null, null, null, false),
('673', null, null, null, null, false),
('674', null, null, null, null, false),
('675', null, null, null, null, false),
('676', null, null, null, null, false),
('677', null, null, null, null, false),
('678', null, null, null, null, false),
('679', null, null, null, null, false),
('680', null, null, null, null, false),
('681', null, null, null, null, false),
('682', null, null, null, null, false),
('683', null, null, null, null, false),
('684', null, null, null, null, false),
('685', null, null, null, null, false),
('686', null, null, null, null, false),
('687', null, null, null, null, false),
('688', null, null, null, null, false),
('689', null, null, null, null, false),
('690', null, null, null, null, false),
('691', null, null, null, null, false),
('692', null, null, null, null, false),
('693', null, null, null, null, false),
('694', null, null, null, null, false),
('695', null, null, null, null, false),
('696', null, null, null, null, false),
('697', null, null, null, null, false),
('698', null, null, null, null, false),
('699', null, null, null, null, false),
('700', 'Revenue', 'income', 'Revenue', 'Total revenue summary', false),
('701', null, null, null, null, false),
('702', null, null, null, null, false),
('703', null, null, null, null, false),
('704', null, null, null, null, false),
('705', null, null, null, null, false),
('706', null, null, null, null, false),
('707', null, null, null, null, false),
('708', null, null, null, null, false),
('709', null, null, null, null, false),
('710', 'Salary & Wages', 'income', 'Revenue', 'Employment income', true),
('711', null, null, null, null, false),
('712', null, null, null, null, false),
('713', null, null, null, null, false),
('714', null, null, null, null, false),
('715', null, null, null, null, false),
('716', null, null, null, null, false),
('717', null, null, null, null, false),
('718', null, null, null, null, false),
('719', null, null, null, null, false),
('720', 'Freelance / Contract', 'income', 'Revenue', null, true),
('721', null, null, null, null, false),
('722', null, null, null, null, false),
('723', null, null, null, null, false),
('724', null, null, null, null, false),
('725', null, null, null, null, false),
('726', null, null, null, null, false),
('727', null, null, null, null, false),
('728', null, null, null, null, false),
('729', null, null, null, null, false),
('730', 'Business Income', 'income', 'Revenue', 'Revenue from business operations', false),
('731', null, null, null, null, false),
('732', null, null, null, null, false),
('733', null, null, null, null, false),
('734', null, null, null, null, false),
('735', null, null, null, null, false),
('736', null, null, null, null, false),
('737', null, null, null, null, false),
('738', null, null, null, null, false),
('739', null, null, null, null, false),
('740', 'Rental Income', 'income', 'Revenue', null, true),
('741', null, null, null, null, false),
('742', null, null, null, null, false),
('743', null, null, null, null, false),
('744', null, null, null, null, false),
('745', null, null, null, null, false),
('746', null, null, null, null, false),
('747', null, null, null, null, false),
('748', null, null, null, null, false),
('749', null, null, null, null, false),
('750', 'Interest Received', 'income', 'Revenue', null, true),
('751', null, null, null, null, false),
('752', null, null, null, null, false),
('753', null, null, null, null, false),
('754', null, null, null, null, false),
('755', null, null, null, null, false),
('756', null, null, null, null, false),
('757', null, null, null, null, false),
('758', null, null, null, null, false),
('759', null, null, null, null, false),
('760', 'Dividend Income', 'income', 'Revenue', null, true),
('761', null, null, null, null, false),
('762', null, null, null, null, false),
('763', null, null, null, null, false),
('764', null, null, null, null, false),
('765', null, null, null, null, false),
('766', null, null, null, null, false),
('767', null, null, null, null, false),
('768', null, null, null, null, false),
('769', null, null, null, null, false),
('770', 'Capital Gains', 'income', 'Revenue', null, false),
('771', null, null, null, null, false),
('772', null, null, null, null, false),
('773', null, null, null, null, false),
('774', null, null, null, null, false),
('775', null, null, null, null, false),
('776', null, null, null, null, false),
('777', null, null, null, null, false),
('778', null, null, null, null, false),
('779', null, null, null, null, false),
('780', 'Government Benefits', 'income', 'Revenue', 'Centrelink, FTB, NDIS etc.', false),
('781', null, null, null, null, false),
('782', null, null, null, null, false),
('783', null, null, null, null, false),
('784', null, null, null, null, false),
('785', null, null, null, null, false),
('786', null, null, null, null, false),
('787', null, null, null, null, false),
('788', null, null, null, null, false),
('789', null, null, null, null, false),
('790', 'Other Income', 'income', 'Revenue', null, false),
('791', null, null, null, null, false),
('792', null, null, null, null, false),
('793', null, null, null, null, false),
('794', null, null, null, null, false),
('795', null, null, null, null, false),
('796', null, null, null, null, false),
('797', null, null, null, null, false),
('798', null, null, null, null, false),
('799', null, null, null, null, false),
('800', 'Housing', 'expense', 'Housing', null, false),
('801', 'Rent / Mortgage', 'expense', 'Housing', null, true),
('802', 'Council Rates', 'expense', 'Housing', null, false),
('803', 'Body Corporate / Strata', 'expense', 'Housing', null, false),
('804', 'Home Insurance', 'expense', 'Housing', null, false),
('805', 'Repairs & Maintenance', 'expense', 'Housing', null, false),
('806', null, null, null, null, false),
('807', null, null, null, null, false),
('808', null, null, null, null, false),
('809', null, null, null, null, false),
('810', 'Utilities', 'expense', 'Utilities', null, false),
('811', 'Electricity', 'expense', 'Utilities', null, true),
('812', 'Gas', 'expense', 'Utilities', null, false),
('813', 'Water', 'expense', 'Utilities', null, false),
('814', 'Internet', 'expense', 'Utilities', null, true),
('815', 'Mobile Phone', 'expense', 'Utilities', null, true),
('816', 'Home Phone', 'expense', 'Utilities', null, false),
('817', null, null, null, null, false),
('818', null, null, null, null, false),
('819', null, null, null, null, false),
('820', 'Groceries', 'expense', 'Living Expenses', null, true),
('821', 'Dining & Takeaway', 'expense', 'Living Expenses', null, true),
('822', 'Coffee', 'expense', 'Living Expenses', null, false),
('823', 'Alcohol & Beverages', 'expense', 'Living Expenses', null, false),
('824', null, null, null, null, false),
('825', null, null, null, null, false),
('826', null, null, null, null, false),
('827', null, null, null, null, false),
('828', null, null, null, null, false),
('829', null, null, null, null, false),
('830', 'Vehicle', 'expense', 'Vehicle', null, false),
('831', 'Fuel & Oil', 'expense', 'Vehicle', null, true),
('832', 'Registration & Insurance', 'expense', 'Vehicle', null, true),
('833', 'Repairs & Servicing', 'expense', 'Vehicle', null, false),
('834', 'Public Transport', 'expense', 'Transport', null, true),
('835', 'Parking & Tolls', 'expense', 'Transport', null, false),
('836', 'Ride Share', 'expense', 'Transport', null, true),
('837', null, null, null, null, false),
('838', null, null, null, null, false),
('839', null, null, null, null, false),
('840', 'Health & Medical', 'expense', 'Health', null, false),
('841', 'Doctor & Specialist', 'expense', 'Health', null, false),
('842', 'Pharmacy & Prescriptions', 'expense', 'Health', null, false),
('843', 'Gym & Fitness', 'expense', 'Health', null, true),
('844', 'Dental', 'expense', 'Health', null, false),
('845', 'Optical', 'expense', 'Health', null, false),
('846', null, null, null, null, false),
('847', null, null, null, null, false),
('848', null, null, null, null, false),
('849', null, null, null, null, false),
('850', 'Entertainment', 'expense', 'Entertainment', null, false),
('851', 'Subscriptions', 'expense', 'Entertainment', 'Streaming, software subscriptions', true),
('852', 'Hobbies', 'expense', 'Entertainment', null, false),
('853', 'Concerts & Events', 'expense', 'Entertainment', null, false),
('854', 'Sport & Recreation', 'expense', 'Entertainment', null, false),
('855', 'Travel & Holidays', 'expense', 'Entertainment', null, true),
('856', 'Accommodation', 'expense', 'Entertainment', null, false),
('857', null, null, null, null, false),
('858', null, null, null, null, false),
('859', null, null, null, null, false),
('860', 'Clothing & Personal Care', 'expense', 'Personal', null, false),
('861', 'Clothing & Shoes', 'expense', 'Personal', null, true),
('862', 'Personal Care & Grooming', 'expense', 'Personal', null, false),
('863', 'Gifts & Donations', 'expense', 'Personal', null, false),
('864', null, null, null, null, false),
('865', null, null, null, null, false),
('866', null, null, null, null, false),
('867', null, null, null, null, false),
('868', null, null, null, null, false),
('869', null, null, null, null, false),
('870', 'Education', 'expense', 'Education', null, false),
('871', 'School & University Fees', 'expense', 'Education', null, false),
('872', 'Books & Supplies', 'expense', 'Education', null, false),
('873', 'Online Courses', 'expense', 'Education', null, false),
('874', null, null, null, null, false),
('875', null, null, null, null, false),
('876', null, null, null, null, false),
('877', null, null, null, null, false),
('878', null, null, null, null, false),
('879', null, null, null, null, false),
('880', 'Financial', 'expense', 'Financial', null, false),
('881', 'Bank Fees & Charges', 'expense', 'Financial', null, true),
('882', 'Life Insurance', 'expense', 'Insurance', null, false),
('883', 'Car Insurance', 'expense', 'Insurance', null, true),
('884', 'Home & Contents Insurance', 'expense', 'Insurance', null, false),
('885', 'Health Insurance', 'expense', 'Insurance', null, true),
('886', 'Income Protection', 'expense', 'Insurance', null, false),
('887', null, null, null, null, false),
('888', null, null, null, null, false),
('889', null, null, null, null, false),
('890', 'Tax & Superannuation', 'expense', 'Tax', null, false),
('891', 'Income Tax', 'expense', 'Tax', null, true),
('892', 'GST', 'expense', 'Tax', null, false),
('893', 'Super Contributions', 'expense', 'Superannuation', null, true),
('894', 'FBT', 'expense', 'Tax', 'Fringe benefits tax', false),
('895', null, null, null, null, false),
('896', null, null, null, null, false),
('897', null, null, null, null, false),
('898', null, null, null, null, false),
('899', null, null, null, null, false),
('900', 'Other Expenses', 'expense', 'Miscellaneous', null, false),
('901', null, null, null, null, false),
('902', null, null, null, null, false),
('903', null, null, null, null, false),
('904', null, null, null, null, false),
('905', null, null, null, null, false),
('906', null, null, null, null, false),
('907', null, null, null, null, false),
('908', null, null, null, null, false),
('909', null, null, null, null, false),
('910', null, null, null, null, false),
('911', null, null, null, null, false),
('912', null, null, null, null, false),
('913', null, null, null, null, false),
('914', null, null, null, null, false),
('915', null, null, null, null, false),
('916', null, null, null, null, false),
('917', null, null, null, null, false),
('918', null, null, null, null, false),
('919', null, null, null, null, false),
('920', null, null, null, null, false),
('921', null, null, null, null, false),
('922', null, null, null, null, false),
('923', null, null, null, null, false),
('924', null, null, null, null, false),
('925', null, null, null, null, false),
('926', null, null, null, null, false),
('927', null, null, null, null, false),
('928', null, null, null, null, false),
('929', null, null, null, null, false),
('930', null, null, null, null, false),
('931', null, null, null, null, false),
('932', null, null, null, null, false),
('933', null, null, null, null, false),
('934', null, null, null, null, false),
('935', null, null, null, null, false),
('936', null, null, null, null, false),
('937', null, null, null, null, false),
('938', null, null, null, null, false),
('939', null, null, null, null, false),
('940', null, null, null, null, false),
('941', null, null, null, null, false),
('942', null, null, null, null, false),
('943', null, null, null, null, false),
('944', null, null, null, null, false),
('945', null, null, null, null, false),
('946', null, null, null, null, false),
('947', null, null, null, null, false),
('948', null, null, null, null, false),
('949', null, null, null, null, false),
('950', null, null, null, null, false),
('951', null, null, null, null, false),
('952', null, null, null, null, false),
('953', null, null, null, null, false),
('954', null, null, null, null, false),
('955', null, null, null, null, false),
('956', null, null, null, null, false),
('957', null, null, null, null, false),
('958', null, null, null, null, false),
('959', null, null, null, null, false),
('960', null, null, null, null, false),
('961', null, null, null, null, false),
('962', null, null, null, null, false),
('963', null, null, null, null, false),
('964', null, null, null, null, false),
('965', null, null, null, null, false),
('966', null, null, null, null, false),
('967', null, null, null, null, false),
('968', null, null, null, null, false),
('969', null, null, null, null, false),
('970', null, null, null, null, false),
('971', null, null, null, null, false),
('972', null, null, null, null, false),
('973', null, null, null, null, false),
('974', null, null, null, null, false),
('975', null, null, null, null, false),
('976', null, null, null, null, false),
('977', null, null, null, null, false),
('978', null, null, null, null, false),
('979', null, null, null, null, false),
('980', null, null, null, null, false),
('981', null, null, null, null, false),
('982', null, null, null, null, false),
('983', null, null, null, null, false),
('984', null, null, null, null, false),
('985', null, null, null, null, false),
('986', null, null, null, null, false),
('987', null, null, null, null, false),
('988', null, null, null, null, false),
('989', null, null, null, null, false),
('990', null, null, null, null, false),
('991', null, null, null, null, false),
('992', null, null, null, null, false),
('993', null, null, null, null, false),
('994', null, null, null, null, false),
('995', null, null, null, null, false),
('996', null, null, null, null, false),
('997', null, null, null, null, false),
('998', null, null, null, null, false),
('999', 'Suspense / Uncategorised', 'expense', 'Miscellaneous', 'Holding account for unclassified items', false)
ON CONFLICT (code) DO UPDATE SET
  label=EXCLUDED.label, type=EXCLUDED.type, group_name=EXCLUDED.group_name,
  description=EXCLUDED.description, is_common=EXCLUDED.is_common;
